blank_issues_enabled: false
contact_links:
  - name: Questions and Support
    url: https://github.com/Skeptic1222/hospital-shift-scheduler/discussions
    about: Please use Discussions for Q&A and general support.

