# ⚠️ CRITICAL WARNING: NEVER ADD DEMO MODE TO THIS APPLICATION
# The client has explicitly forbidden ANY form of demo, mock, or test mode.
# This application REQUIRES a live database connection to function.
# DO NOT add any demo mode, mock data, or bypass mechanisms.

name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        env:
          ADMIN_EMAILS: 'ci-admin@example.com'
        run: npm test -- --watchAll=false

